### ISSUE TITLE
Desktop Background not restored

### ISSUE THREAD

**Issue by JerryF1257** [teejee2008/aptik-plus#7]
Hi Tony,

When I used the new version Aptik 20 to migrate my partner's desktop settings to my laptop, his custom background for his desktop doesn't get restored.

Jerry Ferreira

P.S.  Just read one of your other replies to another issue and it said that you prefer to receive an email.

I will send you an email.

Thanks!

**Comment by teejee2008** [comment]
If some users are logged-in when you do the restore, their desktop sessions will still be running with old settings. The old settings will be saved to disk when they log out or when the system shuts down.

To avoid this issue, log out of all user accounts. Create a new (temporary) user account and login for doing the restore.

Another thing to note is that the old wallpaper must be available on the new system. So if you applied a wallpaper from your home directory it will work fine since home directory data gets restored as well. If you applied a wallpaper from system directory (/usr/share/backgrounds) then the wallpaper must be available on the new system as well.
